# Generated by Django 5.1.2 on 2024-10-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=25)),
                ('product_description', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_img', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
