# Generated by Django 5.1.2 on 2024-10-13 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 13, 12, 6, 11, 692280)),
        ),
    ]
